apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
      - name: main-service
        image: akscircleciacrregistry.azurecr.io/main-service
        #imagePullPolicy: Never
        ports:
        - containerPort: 5000
      - name: sidecar-service
        image: akscircleciacrregistry.azurecr.io/sidecar-service
        #imagePullPolicy: Never
        ports:
        - containerPort: 5000
